Name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:18-alpine3.1515
    steps:
      - name: Log node version
        run: |
          node node-version
          cat /etc/os-release
